name: Build Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: |
          uv sync --dev
      
      - name: Build executable with PyInstaller
        run: |
          uv run pyinstaller --name "Windows Font Changer" `
            --onefile `
            --windowed `
            --icon=icon.ico `
            --add-data "windows_font_changer;windows_font_changer" `
            --hidden-import=PySide6.QtCore `
            --hidden-import=PySide6.QtGui `
            --hidden-import=PySide6.QtWidgets `
            --hidden-import=winreg `
            windows_font_changer/__main__.py
      
      - name: Create portable archive
        run: |
          Compress-Archive -Path "dist\Windows Font Changer.exe" -DestinationPath "WindowsFontChanger-portable.zip"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-font-changer
          path: |
            dist/*.exe
            WindowsFontChanger-portable.zip
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            WindowsFontChanger-portable.zip
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 